# Generated by Django 3.1.3 on 2020-11-14 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusGameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', models.TextField(default=None, null=True)),
                ('phase', models.IntegerField(choices=[(0, 'Phase 1'), (1, 'Phase 2'), (2, 'Phase 3'), (3, 'Finished')], default=0)),
                ('current_player_index', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField(default=None, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bussen.busgamemodel')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rooms.player')),
            ],
        ),
    ]
