# Generated by Django 3.1.2 on 2020-10-21 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusGameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('state', models.TextField(default=None, null=True)),
                ('phase', models.IntegerField(choices=[(0, 'Open for participants'), (1, 'Phase 1'), (2, 'Phase 2'), (3, 'Phase 3'), (4, 'Finished')], default=0)),
                ('current_player_index', models.IntegerField(null=True)),
                ('slug', models.SlugField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.TextField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cookie', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('online', models.BooleanField(default=True)),
                ('last_interaction', models.DateTimeField(auto_now_add=True)),
                ('current_game', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bussen.busgamemodel')),
                ('current_hand', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bussen.hand')),
            ],
        ),
    ]
