# Generated by Django 3.1.2 on 2020-11-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bussen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busgamemodel',
            name='room',
        ),
    ]
