# Generated by Django 3.1.2 on 2020-10-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_player',
            field=models.IntegerField(null=True),
        ),
    ]
