# Generated by Django 3.1.2 on 2020-11-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20201108_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
