# Generated by Django 3.1.2 on 2020-10-13 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20201011_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_interaction',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.IntegerField(choices=[(0, 'Open for participants'), (1, 'Phase 1'), (2, 'Phase 2'), (3, 'Phase 3')], default=0),
        ),
    ]
