# Generated by Django 3.1.2 on 2020-10-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20201013_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='state',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hand',
            name='hand',
            field=models.TextField(),
        ),
    ]
