# Generated by Django 3.1.2 on 2020-10-18 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20201018_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cards_on_pyramid',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='game',
            name='current_card',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(15), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='game',
            name='pyramid',
            field=models.TextField(default='[]'),
        ),
    ]
