# Generated by Django 3.1.2 on 2020-11-12 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20201112_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='online',
        ),
        migrations.AlterField(
            model_name='player',
            name='cookie',
            field=models.CharField(max_length=64),
        ),
    ]
