# Generated by Django 3.1.2 on 2020-10-18 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20201018_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='pyramid',
            new_name='card_list',
        ),
    ]
