# Generated by Django 3.1.2 on 2020-10-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20201018_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='phase',
            field=models.IntegerField(choices=[(0, 'Open for participants'), (1, 'Phase 1'), (2, 'Phase 2'), (3, 'Phase 3'), (4, 'Finished')], default=0),
        ),
    ]
