---

name: "Build Production Docker Image"
if: github.ref == 'refs/heads/master'
on:
  push:
    branches:
      - master

jobs:
  build-docker:
    name: "Build Production Docker Image"
    runs-on: ubuntu-latest
    env:
      DOCKER_LATEST: docker.pkg.github.com/${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY##*/}:latest
      DOCKER_TAG_PRODUCTION: docker.pkg.github.com/${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY##*/}:${GITHUB_SHA}
    steps:

      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: Build and Publish Tag Docker image
        uses: VaultVulp/gp-docker-action@1.1.7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          image-name: games