---

name: "Build Production Docker Image"
on:
  push:
    branches:
      - master

jobs:
  build-docker:
    name: "Build Production Docker Image"
    runs-on: ubuntu-latest
    env:
      DOCKER_LATEST: docker.pkg.github.com/${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY##*/}:latest
      DOCKER_TAG_PRODUCTION: docker.pkg.github.com/${GITHUB_REPOSITORY}/${GITHUB_REPOSITORY##*/}:${GITHUB_SHA}
    steps:

      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: "Build Docker image"
        run: docker build --tag ${DOCKER_LATEST,,} .

      - name: "Login to GitHub"
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u "${{ github.repository_owner }}" --password-stdin

      - name: "Tag and publish"
        run: |
            docker tag "${DOCKER_LATEST,,}" "${DOCKER_TAG_PRODUCTION,,}"
            docker push "${DOCKER_TAG_PRODUCTION,,}"
            docker push "${DOCKER_LATEST,,}"
